"""empty message

Revision ID: 5da605bcf32c
Revises: b7e83c773382
Create Date: 2019-03-19 18:09:54.996562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da605bcf32c'
down_revision = 'b7e83c773382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    op.drop_table('family')
    op.drop_table('join__request')
    op.drop_table('family_identifier')
    op.drop_table('list')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_family')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('current_family', sa.INTEGER(), nullable=True))

    op.create_table('list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('elements', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('user', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_time', sa.VARCHAR(length=100), nullable=False),
    sa.Column('family_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_identifier',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('family_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('join__request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('requester_id', sa.INTEGER(), nullable=True),
    sa.Column('family_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('family', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_time', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['family'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
